# This is a basic workflow to invoke rollback.
name: Rollback Workflow
on: [workflow_dispatch]
jobs:
  execute-rollback:
    runs-on: ubuntu-latest  
    steps:
      - name: Rollback
        id: rollback
        uses: gagoar/invoke-aws-lambda@v3.3.1
        with:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         REGION: us-east-1
         FunctionName: rollbackTest
      - name: Handle response from rollback call
        run:  echo '${{ fromJSON(steps.rollback.outputs.response).Payload }}' > invocation-response.json
